"""empty message

Revision ID: 1bd909ad4014
Revises: bbff4f8394c0
Create Date: 2024-08-11 20:46:40.528545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd909ad4014'
down_revision = 'bbff4f8394c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atividade_numero', sa.Integer(), nullable=False))
        batch_op.drop_column('atividade_num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('atividade_num', sa.INTEGER(), nullable=False))
        batch_op.drop_column('atividade_numero')

    # ### end Alembic commands ###
