"""empty message

Revision ID: 3de777f25400
Revises: 8e7b922b9584
Create Date: 2024-07-30 12:13:40.866916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de777f25400'
down_revision = '8e7b922b9584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('mensagem', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('turma_id')
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('atividade', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('turma_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'post', ['turma_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('mensagem')
        batch_op.drop_column('data_criacao')

    # ### end Alembic commands ###
